// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package relationclient

import (
	"context"

	"github.com/huangsihao7/scooter-WSVA/relation/rpc/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FavoriteListReq   = relation.FavoriteListReq
	FavoriteListResp  = relation.FavoriteListResp
	FavoriteRequest   = relation.FavoriteRequest
	FavoriteResponse  = relation.FavoriteResponse
	FollowCountReq    = relation.FollowCountReq
	FollowCountResp   = relation.FollowCountResp
	FollowerCountReq  = relation.FollowerCountReq
	FollowerCountResp = relation.FollowerCountResp
	FollowerListReq   = relation.FollowerListReq
	FollowerListResp  = relation.FollowerListResp
	FriendListReq     = relation.FriendListReq
	FriendListResp    = relation.FriendListResp
	IsFollowingReq    = relation.IsFollowingReq
	IsFollowingResp   = relation.IsFollowingResp
	UserInfo          = relation.UserInfo

	Relation interface {
		Favorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error)
		FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error)
		FollowerList(ctx context.Context, in *FollowerListReq, opts ...grpc.CallOption) (*FollowerListResp, error)
		FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error)
		GetFollowCount(ctx context.Context, in *FollowCountReq, opts ...grpc.CallOption) (*FollowCountResp, error)
		GetFollowerCount(ctx context.Context, in *FollowerCountReq, opts ...grpc.CallOption) (*FollowerCountResp, error)
		IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error)
	}

	defaultRelation struct {
		cli zrpc.Client
	}
)

func NewRelation(cli zrpc.Client) Relation {
	return &defaultRelation{
		cli: cli,
	}
}

func (m *defaultRelation) Favorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.Favorite(ctx, in, opts...)
}

func (m *defaultRelation) FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}

func (m *defaultRelation) FollowerList(ctx context.Context, in *FollowerListReq, opts ...grpc.CallOption) (*FollowerListResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.FollowerList(ctx, in, opts...)
}

func (m *defaultRelation) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}

func (m *defaultRelation) GetFollowCount(ctx context.Context, in *FollowCountReq, opts ...grpc.CallOption) (*FollowCountResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.GetFollowCount(ctx, in, opts...)
}

func (m *defaultRelation) GetFollowerCount(ctx context.Context, in *FollowerCountReq, opts ...grpc.CallOption) (*FollowerCountResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.GetFollowerCount(ctx, in, opts...)
}

func (m *defaultRelation) IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.IsFollowing(ctx, in, opts...)
}
