// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package relationclient

import (
	"context"

	"github.com/huangsihao7/scooter-WSVA/relation/rpc/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FavoriteListReq  = relation.FavoriteListReq
	FavoriteListResp = relation.FavoriteListResp
	FavoriteRequest  = relation.FavoriteRequest
	FavoriteResponse = relation.FavoriteResponse
	FollowerListReq  = relation.FollowerListReq
	FollowerListResp = relation.FollowerListResp
	FriendListReq    = relation.FriendListReq
	FriendListResp   = relation.FriendListResp
	UserInfo         = relation.UserInfo

	Relation interface {
		Favorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error)
		FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error)
		FollowerList(ctx context.Context, in *FollowerListReq, opts ...grpc.CallOption) (*FollowerListResp, error)
		FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error)
	}

	defaultRelation struct {
		cli zrpc.Client
	}
)

func NewRelation(cli zrpc.Client) Relation {
	return &defaultRelation{
		cli: cli,
	}
}

func (m *defaultRelation) Favorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*FavoriteResponse, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.Favorite(ctx, in, opts...)
}

func (m *defaultRelation) FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}

func (m *defaultRelation) FollowerList(ctx context.Context, in *FollowerListReq, opts ...grpc.CallOption) (*FollowerListResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.FollowerList(ctx, in, opts...)
}

func (m *defaultRelation) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}
