// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
	Dec      string `json:"dec"`
}

type RegisterResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Avatar string `json:"avatar"`
	Dec    string `json:"dec"`
}

type UserInfoReq struct {
	Uid int64 `json:"uid"`
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Avatar string `json:"avatar"`
	Dec    string `json:"dec"`
}

type UserUploadResponse struct {
	Url      string `json:"url"`
	CoverUrl string `json:"coverUrl"`
}
