// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	StatusCode      int    `json:"status_code"`
	StatusMsg       string `json:"status_msg"`
	Avatar          string `json:"avatar"`
	AccessToken     string `json:"accessToken"`
	UserID          int64  `json:"user_id"`
	Name            string `json:"name"`
	Gender          uint32 `json:"gender"`
	Signature       string `json:"signature"`
	BackgroundImage string `json:"background_image"` //用户个人页顶部大图
}

type RegisterRequest struct {
	Name            string `json:"name"`
	Gender          int64  `json:"gender"`
	Mobile          string `json:"mobile"`
	Password        string `json:"password"`
	Dec             string `json:"dec"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
}

type RegisterResponse struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type UploadImageResponse struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	Url        string `json:"url"`
}

type UpdateRequest struct {
	Name            string `json:"name,optional"`
	Gender          int64  `json:"gender,optional"`
	Avatar          string `json:"avatar,optional"`
	Dec             string `json:"dec,optional"`
	BackgroundImage string `json:"background_image,optional"`
}

type UpdateResponse struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type UserInfoReq struct {
	Uid int64 `json:"uid"`
}

type UserInfoResponse struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	User       User   `json:"user"`
}

type User struct {
	Id              uint32 `json:"id"`
	Name            string `json:"name"`
	Avatar          string `json:"avatar"`
	Gender          uint32 `json:"gender"`
	Signature       string `json:"signature"`
	BackgroundImage string `json:"background_image"` //用户个人页顶部大图
	FollowCount     uint32 `json:"follow_count"`
	FollowerCount   uint32 `json:"follower_count"`
	TotalFavorited  uint32 `json:"total_favorited"`
	WorkCount       uint32 `json:"work_count"`
	FavoriteCount   uint32 `json:"favorite_count"`
	IsFollow        bool   `json:"is_follow"`
	FriendCount     int64  `json:"friend_count"`
}

type UserUploadResponse struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	Url        string `json:"url"`
	CoverUrl   string `json:"coverUrl"`
}
