// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Avatar      string `json:"avatar"`
	AccessToken string `json:"accessToken"`
	UserID      int64  `json:"user_id"`
	StatusCode  int    `json:"status_code"`
	StatusMsg   string `json:"status_msg"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
	Dec      string `json:"dec"`
}

type RegisterResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Avatar string `json:"avatar"`
	Dec    string `json:"dec"`
}

type UserInfoReq struct {
	Uid int64 `json:"uid"`
}

type UserInfoResponse struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	User       User   `json:"user"`
}

type User struct {
	Id             uint32 `json:"id"`
	Name           string `json:"name"`
	Avatar         string `json:"avatar"`
	Signature      string `json:"signature"`
	FollowCount    uint32 `json:"follow_count"`
	FollowerCount  uint32 `json:"follower_count"`
	TotalFavorited uint32 `json:"total_favorited"`
	WorkCount      uint32 `json:"work_count"`
	FavoriteCount  uint32 `json:"favorite_count"`
	IsFollow       bool   `json:"is_follow"`
}

type UserUploadResponse struct {
	Url      string `json:"url"`
	CoverUrl string `json:"coverUrl"`
}
