/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentCom: typeof import('./src/components/comment/CommentCom.vue')['default']
    CommentListCom: typeof import('./src/components/comment/CommentListCom.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    InfoEditCom: typeof import('./src/components/myinfo/InfoEditCom.vue')['default']
    MyHeaderCom: typeof import('./src/components/myinfo/MyHeaderCom.vue')['default']
    MyInteractCom: typeof import('./src/components/myinfo/MyInteractCom.vue')['default']
    PostVideo: typeof import('./src/components/video/PostVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/SubMenu.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    VideoCard: typeof import('./src/components/VideoCard.vue')['default']
    VideoCardList: typeof import('./src/components/video/VideoCardList.vue')['default']
    VideoCom: typeof import('./src/components/video/VideoCom.vue')['default']
    VideoList: typeof import('./src/components/VideoList.vue')['default']
    VideoPlus: typeof import('./src/components/video/VideoPlus.vue')['default']
    VideoRecommendCard: typeof import('./src/components/video/VideoRecommendCard.vue')['default']
  }
}
