/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentCom: typeof import('./src/components/comment/CommentCom.vue')['default']
    CommentListCom: typeof import('./src/components/comment/CommentListCom.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    InfoEditCom: typeof import('./src/components/myinfo/InfoEditCom.vue')['default']
    MyHeaderCom: typeof import('./src/components/myinfo/MyHeaderCom.vue')['default']
    MyInteractCom: typeof import('./src/components/myinfo/MyInteractCom.vue')['default']
    PostVideo: typeof import('./src/components/video/PostVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/SubMenu.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    VideoCard: typeof import('./src/components/VideoCard.vue')['default']
    VideoCardList: typeof import('./src/components/video/VideoCardList.vue')['default']
    VideoCom: typeof import('./src/components/video/VideoCom.vue')['default']
    VideoList: typeof import('./src/components/VideoList.vue')['default']
    VideoPlus: typeof import('./src/components/video/VideoPlus.vue')['default']
  }
}
