stages:
  - install
  - build
  - deploy
.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/
    key: ${CI_COMMIT_REF_SLUG}_backend
install-backend:
  image: golang:1.20.3
  stage: install
  extends: .go-cache
  variables:
    GOPROXY: https://goproxy.cn
  script:
    - cd backend
    - make download
    - export PATH=$PATH:$GOPATH/bin
    - source ~/.profile
    - make doc
    - make build
  artifacts:
    expire_in: 1 day
    paths:
      - backend/output
      - swagger/api
install-frontend:
  image: node:20.9.0-bullseye
  stage: install
  cache:
    paths:
      - frontend/node_modules/
    key: ${CI_COMMIT_REF_SLUG}_frontend
  script:
    - cd frontend
    - npm install --registry=https://registry.npmmirror.com/
    - npm run lint
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - frontend/dist

build-ml-image:
  image: docker:dind
  stage: build
  services:
    - docker:dind
  tags:
    - "gpu"
  only:
    refs:
      - main
    # changes:
    #   - ML/**/*
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 172.22.121.50
  script:
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-ml:$CI_PIPELINE_IID" \
      -f ML/Dockerfile \
      ./ML
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-ml:$CI_PIPELINE_IID"
build-backend-image:
  image: docker:dind
  stage: build
  services:
    - docker:dind
  only:
    refs:
      - main
    # changes:
    #   - backend/**/*
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 172.22.121.50
  script:
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-comment-api:$CI_PIPELINE_IID" \
      -f backend/deployments/comment_api.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-comment-rpc:$CI_PIPELINE_IID" \
      -f backend/deployments/comment_rpc.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-favorite-api:$CI_PIPELINE_IID" \
      -f backend/deployments/favorite_api.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-favorite-rpc:$CI_PIPELINE_IID" \
      -f backend/deployments/favorite_rpc.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-feed-api:$CI_PIPELINE_IID" \
      -f backend/deployments/feed_api.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-feed-rpc:$CI_PIPELINE_IID" \
      -f backend/deployments/feed_rpc.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-relation-api:$CI_PIPELINE_IID" \
      -f backend/deployments/relation_api.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-relation-rpc:$CI_PIPELINE_IID" \
      -f backend/deployments/relation_rpc.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-user-api:$CI_PIPELINE_IID" \
      -f backend/deployments/user_api.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-user-rpc:$CI_PIPELINE_IID" \
      -f backend/deployments/user_rpc.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-mq-api:$CI_PIPELINE_IID" \
      -f backend/deployments/mq_api.Dockerfile \
      ./backend
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-label-rpc:$CI_PIPELINE_IID" \
      -f backend/deployments/label_rpc.Dockerfile \
      ./backend
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-comment-api:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-comment-rpc:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-favorite-api:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-favorite-rpc:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-feed-api:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-feed-rpc:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-relation-api:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-relation-rpc:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-user-api:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-user-rpc:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-mq-api:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-label-rpc:$CI_PIPELINE_IID"
build-nginx-image:
  image: docker:dind
  stage: build
  services:
    - docker:dind
  only:
    refs:
      - main
    # changes:
    #   - scripts/nginx/**/*
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 172.22.121.50
  script:
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-nginx:$CI_PIPELINE_IID" \
      -f scripts/nginx/Dockerfile \
      ./scripts/nginx
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-swagger:$CI_PIPELINE_IID" \
      -f scripts/swagger/Dockerfile \
      ./scripts/swagger
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-nginx:$CI_PIPELINE_IID"
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-swagger:$CI_PIPELINE_IID"
build-frontend-image:
  image: docker:dind
  stage: build
  services:
    - docker:dind
  only:
    refs:
      - main
    # changes:
    #   - scripts/nginx/**/*
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 172.22.121.50
  script:
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-frontend:$CI_PIPELINE_IID" \
      -f frontend/Dockerfile \
      ./frontend
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-frontend:$CI_PIPELINE_IID"

deploy-ml:
  stage: deploy
  tags:
    - "54"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push" && $CI_MERGE_REQUEST_EVENT_TYPE == null'
    # - when: on_failure
    #   exists:
    #     - build-ml-image
  variables:
    GIT_STRATEGY: none
  script:
    - echo "=======start deploy======="
    - docker rm -f scooter-wsva-ml
    - |
      docker run \
      -di \
      -p 8000:8000 \
      --name scooter-wsva-ml \
      -e DEVICE=cuda \
      -e SPARK_APPID=$SPARK_APPID \
      -e SPARK_API_KEY=$SPARK_API_KEY \
      -e SPARK_API_SECRET=$SPARK_API_SECRET \
      -e WHISPER_MODEL_PATH=/root/.cache/huggingface/hub/models--openai--whisper-large-v2/snapshots/696465c62215e36a9ab3f9b7672fe7749f1a1df5 \
      -v /root/.cache/huggingface/:/root/.cache/huggingface:ro \
      172.22.121.50/ai-evaluation/scooter-wsva-ml:$CI_PIPELINE_IID
    - echo "=======deploy success======="
deploy-backend:
  stage: deploy
  tags:
    - "53"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push" && $CI_MERGE_REQUEST_EVENT_TYPE == null'
    # - when: on_failure
    #   exists:
    #     - build-backend-image
  variables:
    GIT_STRATEGY: none
  script:
    - echo "=======start deploy======="
    - docker rm -f scooter-wsva-user-rpc
    - |
      docker run \
      -di \
      -p 8020:8020 \
      --name scooter-wsva-user-rpc \
      172.22.121.50/ai-evaluation/scooter-wsva-user-rpc:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-feed-rpc
    - |
      docker run \
      -di \
      -p 8011:8011 \
      --name scooter-wsva-feed-rpc \
      172.22.121.50/ai-evaluation/scooter-wsva-feed-rpc:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-favorite-rpc
    - |
      docker run \
      -di \
      -p 8012:8012 \
      --name scooter-wsva-favorite-rpc \
      172.22.121.50/ai-evaluation/scooter-wsva-favorite-rpc:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-relation-rpc
    - |
      docker run \
      -di \
      -p 8013:8013 \
      --name scooter-wsva-relation-rpc \
      172.22.121.50/ai-evaluation/scooter-wsva-relation-rpc:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-comment-rpc
    - |
      docker run \
      -di \
      -p 8014:8014 \
      --name scooter-wsva-comment-rpc \
      172.22.121.50/ai-evaluation/scooter-wsva-comment-rpc:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-label-rpc
    - |
      docker run \
      -di \
      -p 8016:8016 \
      --name scooter-wsva-label-rpc \
      172.22.121.50/ai-evaluation/scooter-wsva-label-rpc:$CI_PIPELINE_IID
    - sleep 10
    - docker rm -f scooter-wsva-user-api
    - |
      docker run \
      -di \
      -p 8890:8890 \
      --name scooter-wsva-user-api \
      172.22.121.50/ai-evaluation/scooter-wsva-user-api:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-feed-api
    - |
      docker run \
      -di \
      -p 8891:8891 \
      --name scooter-wsva-feed-api \
      172.22.121.50/ai-evaluation/scooter-wsva-feed-api:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-favorite-api
    - |
      docker run \
      -di \
      -p 8892:8892 \
      --name scooter-wsva-favorite-api \
      172.22.121.50/ai-evaluation/scooter-wsva-favorite-api:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-relation-api
    - |
      docker run \
      -di \
      -p 8893:8893 \
      --name scooter-wsva-relation-api \
      172.22.121.50/ai-evaluation/scooter-wsva-relation-api:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-comment-api
    - |
      docker run \
      -di \
      -p 8894:8894 \
      --name scooter-wsva-comment-api \
      172.22.121.50/ai-evaluation/scooter-wsva-comment-api:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-mq-api
    - |
      docker run \
      -di \
      -p 8895:8895 \
      --name scooter-wsva-mq-api \
      172.22.121.50/ai-evaluation/scooter-wsva-mq-api:$CI_PIPELINE_IID
    - echo "=======deploy success======="
deploy-nginx:
  stage: deploy
  tags:
    - "53"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push" && $CI_MERGE_REQUEST_EVENT_TYPE == null'
    # - when: on_failure
    #   exists:
    #     - build-nginx-image
  variables:
    GIT_STRATEGY: none
  script:
    - echo "=======start deploy======="
    - docker rm -f scooter-wsva-nginx
    - |
      docker run \
      -di \
      -p 7070:80 \
      --name scooter-wsva-nginx \
      172.22.121.50/ai-evaluation/scooter-wsva-nginx:$CI_PIPELINE_IID
    - docker rm -f scooter-wsva-swagger
    - |
      docker run \
      -di \
      -p 7071:10000 \
      --name scooter-wsva-swagger \
      172.22.121.50/ai-evaluation/scooter-wsva-swagger:$CI_PIPELINE_IID
    - echo "=======deploy success======="
deploy-frontend:
  stage: deploy
  tags:
    - "53"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push" && $CI_MERGE_REQUEST_EVENT_TYPE == null'
    # - when: on_failure
    #   exists:
    #     - build-nginx-image
  variables:
    GIT_STRATEGY: none
  script:
    - echo "=======start deploy======="
    - docker rm -f scooter-wsva-frontend
    - |
      docker run \
      -di \
      -p 80:80 \
      --name scooter-wsva-frontend \
      172.22.121.50/ai-evaluation/scooter-wsva-frontend:$CI_PIPELINE_IID
    - echo "=======deploy success======="
