stages:
  - build
  - deploy
build-ml-image:
  image: docker:dind
  stage: build
  services:
    - docker:dind
  tags:
    - "gpu"
  only:
    refs:
      - main
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 172.22.121.50
  script:
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-ml:$CI_PIPELINE_IID" \
      -f ML/Dockerfile \
      ./ML
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-ml:$CI_PIPELINE_IID"

build-backend-image:
  image: docker:dind
  stage: build
  services:
    - docker:dind
  only:
    refs:
      - main
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 172.22.121.50
  script:
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-backend:$CI_PIPELINE_IID" \
      -f backend/Dockerfile \
      ./backend
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-backend:$CI_PIPELINE_IID"
build-nginx-image:
  image: docker:dind
  stage: build
  services:
    - docker:dind
  only:
    refs:
      - main
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 172.22.121.50
  script:
    - |
      docker build \
      -t "172.22.121.50/ai-evaluation/scooter-wsva-nginx:$CI_PIPELINE_IID" \
      -f backend/nginx.Dockerfile \
      ./backend
    - docker push "172.22.121.50/ai-evaluation/scooter-wsva-nginx:$CI_PIPELINE_IID"

deploy-ml:
  stage: deploy
  tags:
    - "54"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push" && $CI_MERGE_REQUEST_EVENT_TYPE == null'
  variables:
    GIT_STRATEGY: none
  script:
    - echo "=======start deploy======="
    - docker rm -f scooter-wsva-ml
    - |
      docker run \
      -di \
      -p 8000:8000 \
      --name scooter-wsva-ml \
      -e DEVICE=cuda \
      -e SPARK_APPID=$SPARK_APPID \
      -e SPARK_API_KEY=$SPARK_API_KEY \
      -e SPARK_API_SECRET=$SPARK_API_SECRET \
      -e WHISPER_MODEL_PATH=/root/.cache/huggingface/hub/models--openai--whisper-large-v2/snapshots/696465c62215e36a9ab3f9b7672fe7749f1a1df5 \
      -v /root/.cache/huggingface/:/root/.cache/huggingface:ro \
      172.22.121.50/ai-evaluation/scooter-wsva-ml:$CI_PIPELINE_IID
    - echo "=======deploy success======="
deploy-backend:
  stage: deploy
  tags:
    - "53"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push" && $CI_MERGE_REQUEST_EVENT_TYPE == null'
  variables:
    GIT_STRATEGY: none
  script:
    - echo "=======start deploy======="
    - docker rm -f scooter-wsva-backend
    - |
      docker run \
      -di \
      -p 8890:8890 \
      -p 8891:8891 \
      -p 8892:8892 \
      -p 8893:8893 \
      -p 8894:8894 \
      --name scooter-wsva-backend \
      172.22.121.50/ai-evaluation/scooter-wsva-backend:$CI_PIPELINE_IID
    - echo "=======deploy success======="
deploy-nginx:
  stage: deploy
  tags:
    - "53"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push" && $CI_MERGE_REQUEST_EVENT_TYPE == null'
  variables:
    GIT_STRATEGY: none
  script:
    - echo "=======start deploy======="
    - docker rm -f scooter-wsva-nginx
    - |
      docker run \
      -di \
      -p 7070:80 \
      --name scooter-wsva-nginx \
      172.22.121.50/ai-evaluation/scooter-wsva-nginx:$CI_PIPELINE_IID
    - echo "=======deploy success======="