// Code generated by goctl. DO NOT EDIT.
package types

type ActionReq struct {
	ToUserId int64 `json:"to_user_id"` //关注谁
	Action   int32 `json:"action"`     // 1 关注 2 是取关 其他是报错
}

type ActionResp struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}
