// Code generated by goctl. DO NOT EDIT.
package types

type ActionReq struct {
	ToUserId int64 `json:"to_user_id"`  //关注谁
	Action   int32 `json:"action_type"` // 1 关注 2 是取关 其他是报错
}

type ActionResp struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type FavoriteListReq struct {
	Uid int64 `form:"uid"`
}

type UserInfo struct {
	Id              int64  `json:"id"`
	Name            string `json:"name"`
	Gender          int64  `json:"gender"`
	Mobile          string `json:"mobile"`
	Avatar          string `json:"avatar"`
	Dec             string `json:"dec"`
	BackgroundImage string `json:"background_image"`
	FollowCount     uint32 `json:"follow_count"`
	FollowerCount   uint32 `json:"follower_count"`
	TotalFavorited  uint32 `json:"total_favorited"`
	WorkCount       uint32 `json:"work_count"`
	FavoriteCount   uint32 `json:"favorite_count"`
	IsFollow        bool   `json:"is_follow"`
	CoverUrl        string `json:"cover_url"`
	VideoId         int64  `json:"video_id"`
	FriendCount     int64  `json:"friend_count"`
}

type FavoriteListResp struct {
	StatusCode int        `json:"status_code"`
	StatusMsg  string     `json:"status_msg"`
	List       []UserInfo `json:"list"`
}

type FollowerListReq struct {
	Uid int64 `form:"uid"`
}

type FollowerListResp struct {
	StatusCode int        `json:"status_code"`
	StatusMsg  string     `json:"status_msg"`
	List       []UserInfo `json:"list"`
}

type FriendListReq struct {
	Uid int64 `form:"uid"`
}

type FriendListResp struct {
	StatusCode int        `json:"status_code"`
	StatusMsg  string     `json:"status_msg"`
	List       []UserInfo `json:"list"`
}
