// Code generated by goctl. DO NOT EDIT.
// Source: feed.proto

package feedsrv

import (
	"context"

	"github.com/huangsihao7/scooter-WSVA/feed/rpc/feed"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PublishListRequest  = feed.PublishListRequest
	PublishListResponse = feed.PublishListResponse
	User                = feed.User
	Video               = feed.Video

	FeedSrv interface {
		PublishList(ctx context.Context, in *PublishListRequest, opts ...grpc.CallOption) (*PublishListResponse, error)
	}

	defaultFeedSrv struct {
		cli zrpc.Client
	}
)

func NewFeedSrv(cli zrpc.Client) FeedSrv {
	return &defaultFeedSrv{
		cli: cli,
	}
}

func (m *defaultFeedSrv) PublishList(ctx context.Context, in *PublishListRequest, opts ...grpc.CallOption) (*PublishListResponse, error) {
	client := feed.NewFeedSrvClient(m.cli.Conn())
	return client.PublishList(ctx, in, opts...)
}
