// Code generated by goctl. DO NOT EDIT.
// Source: label.proto

package server

import (
	"context"

	"github.com/huangsihao7/scooter-WSVA/label/rpc/internal/logic"
	"github.com/huangsihao7/scooter-WSVA/label/rpc/internal/svc"
	"github.com/huangsihao7/scooter-WSVA/label/rpc/label"
)

type LabelServer struct {
	svcCtx *svc.ServiceContext
	label.UnimplementedLabelServer
}

func NewLabelServer(svcCtx *svc.ServiceContext) *LabelServer {
	return &LabelServer{
		svcCtx: svcCtx,
	}
}

func (s *LabelServer) InsertLabel(ctx context.Context, in *label.InsertLabelReq) (*label.InsertLabelResp, error) {
	l := logic.NewInsertLabelLogic(ctx, s.svcCtx)
	return l.InsertLabel(in)
}
