// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package usesrv

import (
	"context"

	"github.com/huangsihao7/scooter-WSVA/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest     = user.LoginRequest
	LoginResponse    = user.LoginResponse
	RegisterRequest  = user.RegisterRequest
	RegisterResponse = user.RegisterResponse
	User             = user.User
	UserInfoRequest  = user.UserInfoRequest
	UserInfoResponse = user.UserInfoResponse

	UseSrv interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	}

	defaultUseSrv struct {
		cli zrpc.Client
	}
)

func NewUseSrv(cli zrpc.Client) UseSrv {
	return &defaultUseSrv{
		cli: cli,
	}
}

func (m *defaultUseSrv) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUseSrvClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUseSrv) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUseSrvClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUseSrv) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUseSrvClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}
