// Code generated by goctl. DO NOT EDIT.
// Source: live.proto

package server

import (
	"context"

	"github.com/huangsihao7/scooter-WSVA/live/rpc/internal/logic"
	"github.com/huangsihao7/scooter-WSVA/live/rpc/internal/svc"
	"github.com/huangsihao7/scooter-WSVA/live/rpc/live"
)

type LiveServer struct {
	svcCtx *svc.ServiceContext
	live.UnimplementedLiveServer
}

func NewLiveServer(svcCtx *svc.ServiceContext) *LiveServer {
	return &LiveServer{
		svcCtx: svcCtx,
	}
}

// 开启直播
func (s *LiveServer) StartLive(ctx context.Context, in *live.StartLiveRequest) (*live.StartLiveResponse, error) {
	l := logic.NewStartLiveLogic(ctx, s.svcCtx)
	return l.StartLive(in)
}

// 查看直播列表
func (s *LiveServer) ListVideo(ctx context.Context, in *live.ListLiveRequest) (*live.ListLiveResponse, error) {
	l := logic.NewListVideoLogic(ctx, s.svcCtx)
	return l.ListVideo(in)
}
