// Code generated by goctl. DO NOT EDIT.
// Source: recommend.proto

package server

import (
	"context"

	"github.com/huangsihao7/scooter-WSVA/recommend/rpc/internal/logic"
	"github.com/huangsihao7/scooter-WSVA/recommend/rpc/internal/svc"
	"github.com/huangsihao7/scooter-WSVA/recommend/rpc/recommend"
)

type RecommendSrvServer struct {
	svcCtx *svc.ServiceContext
	recommend.UnimplementedRecommendSrvServer
}

func NewRecommendSrvServer(svcCtx *svc.ServiceContext) *RecommendSrvServer {
	return &RecommendSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *RecommendSrvServer) CreateVideo(ctx context.Context, in *recommend.CreateVideoRequest) (*recommend.CreateVideoResponse, error) {
	l := logic.NewCreateVideoLogic(ctx, s.svcCtx)
	return l.CreateVideo(in)
}
