// Code generated by goctl. DO NOT EDIT.
package types

type CreateVideoReq struct {
	Url      string `json:"url"` //视频地址
	CoverUrl string `json:"coverUrl"`
	Title    string `json:"title"`
	Category string `json:"category"`
}

type CreateVideoResp struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}
