// Code generated by goctl. DO NOT EDIT.
// Source: feed.proto

package server

import (
	"context"

	"github.com/huangsihao7/scooter-WSVA/feed/rpc/feed"
	"github.com/huangsihao7/scooter-WSVA/feed/rpc/internal/logic"
	"github.com/huangsihao7/scooter-WSVA/feed/rpc/internal/svc"
)

type FeedSrvServer struct {
	svcCtx *svc.ServiceContext
	feed.UnimplementedFeedSrvServer
}

func NewFeedSrvServer(svcCtx *svc.ServiceContext) *FeedSrvServer {
	return &FeedSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *FeedSrvServer) PublishList(ctx context.Context, in *feed.PublishListRequest) (*feed.PublishListResponse, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}
