// Code generated by goctl. DO NOT EDIT.
package types

type ActionReq struct {
	Vid    int64 `form:"vid"`
	Action int32 `form:"action"`
}

type ActionResp struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type ListReq struct {
}

type ListResp struct {
}

type Response struct {
}
