// Code generated by goctl. DO NOT EDIT.
package types

type ActionReq struct {
	VideoId     int64  `json:"video_id"`     // 视频id
	ActionType  int32  `json:"action_type"`  // 1-发布评论，2-删除评论
	CommentText string `json:"comment_text"` // 用户填写的评论内容，在action_type=1的时候使用
	CommentId   int64  `json:"comment_id"`   // 要删除的评论id，在action_type=2的时候使用
}

type ActionResp struct {
	StatusCode  int    `json:"status_code"`
	StatusMsg   string `json:"status_msg"`
	CommentText string `json:"comment_text"` // 返回用户评论的内容
}

type ListReq struct {
}

type ListResp struct {
}

type Response struct {
}
