// Code generated by goctl. DO NOT EDIT.
// Source: feed.proto

package feedclient

import (
	"context"

	"github.com/huangsihao7/scooter-WSVA/feed/rpc/feed"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CategoryFeedRequest  = feed.CategoryFeedRequest
	CategoryFeedResponse = feed.CategoryFeedResponse
	CountVideoRequest    = feed.CountVideoRequest
	CountVideoResponse   = feed.CountVideoResponse
	CreateVideoRequest   = feed.CreateVideoRequest
	CreateVideoResponse  = feed.CreateVideoResponse
	DeleteVideoReq       = feed.DeleteVideoReq
	DeleteVideoResp      = feed.DeleteVideoResp
	EsSearchReq          = feed.EsSearchReq
	EsSearchResp         = feed.EsSearchResp
	FindVideoReq         = feed.FindVideoReq
	FindVideoResp        = feed.FindVideoResp
	HistoryReq           = feed.HistoryReq
	HistoryResp          = feed.HistoryResp
	ListFeedRequest      = feed.ListFeedRequest
	ListFeedResponse     = feed.ListFeedResponse
	ListVideoRequest     = feed.ListVideoRequest
	ListVideoResponse    = feed.ListVideoResponse
	NeighborsReq         = feed.NeighborsReq
	NeighborsResp        = feed.NeighborsResp
	User                 = feed.User
	VideoDurationReq     = feed.VideoDurationReq
	VideoDurationResp    = feed.VideoDurationResp
	VideoInfo            = feed.VideoInfo

	Feed interface {
		CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error)
		ListVideo(ctx context.Context, in *ListVideoRequest, opts ...grpc.CallOption) (*ListVideoResponse, error)
		ListVideosByRecommend(ctx context.Context, in *ListFeedRequest, opts ...grpc.CallOption) (*ListFeedResponse, error)
		ListVideos(ctx context.Context, in *ListFeedRequest, opts ...grpc.CallOption) (*ListFeedResponse, error)
		ListCategoryVideos(ctx context.Context, in *CategoryFeedRequest, opts ...grpc.CallOption) (*CategoryFeedResponse, error)
		ListPopularVideos(ctx context.Context, in *ListFeedRequest, opts ...grpc.CallOption) (*ListFeedResponse, error)
		CreateVideoTest(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error)
		VideoDuration(ctx context.Context, in *VideoDurationReq, opts ...grpc.CallOption) (*VideoDurationResp, error)
		ListHistoryVideos(ctx context.Context, in *HistoryReq, opts ...grpc.CallOption) (*HistoryResp, error)
		ListNeighborVideos(ctx context.Context, in *NeighborsReq, opts ...grpc.CallOption) (*NeighborsResp, error)
		DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error)
		SearchES(ctx context.Context, in *EsSearchReq, opts ...grpc.CallOption) (*EsSearchResp, error)
		FindVideo(ctx context.Context, in *FindVideoReq, opts ...grpc.CallOption) (*FindVideoResp, error)
	}

	defaultFeed struct {
		cli zrpc.Client
	}
)

func NewFeed(cli zrpc.Client) Feed {
	return &defaultFeed{
		cli: cli,
	}
}

func (m *defaultFeed) CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.CreateVideo(ctx, in, opts...)
}

func (m *defaultFeed) ListVideo(ctx context.Context, in *ListVideoRequest, opts ...grpc.CallOption) (*ListVideoResponse, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.ListVideo(ctx, in, opts...)
}

func (m *defaultFeed) ListVideosByRecommend(ctx context.Context, in *ListFeedRequest, opts ...grpc.CallOption) (*ListFeedResponse, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.ListVideosByRecommend(ctx, in, opts...)
}

func (m *defaultFeed) ListVideos(ctx context.Context, in *ListFeedRequest, opts ...grpc.CallOption) (*ListFeedResponse, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.ListVideos(ctx, in, opts...)
}

func (m *defaultFeed) ListCategoryVideos(ctx context.Context, in *CategoryFeedRequest, opts ...grpc.CallOption) (*CategoryFeedResponse, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.ListCategoryVideos(ctx, in, opts...)
}

func (m *defaultFeed) ListPopularVideos(ctx context.Context, in *ListFeedRequest, opts ...grpc.CallOption) (*ListFeedResponse, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.ListPopularVideos(ctx, in, opts...)
}

func (m *defaultFeed) CreateVideoTest(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*CreateVideoResponse, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.CreateVideoTest(ctx, in, opts...)
}

func (m *defaultFeed) VideoDuration(ctx context.Context, in *VideoDurationReq, opts ...grpc.CallOption) (*VideoDurationResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.VideoDuration(ctx, in, opts...)
}

func (m *defaultFeed) ListHistoryVideos(ctx context.Context, in *HistoryReq, opts ...grpc.CallOption) (*HistoryResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.ListHistoryVideos(ctx, in, opts...)
}

func (m *defaultFeed) ListNeighborVideos(ctx context.Context, in *NeighborsReq, opts ...grpc.CallOption) (*NeighborsResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.ListNeighborVideos(ctx, in, opts...)
}

func (m *defaultFeed) DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.DeleteVideo(ctx, in, opts...)
}

func (m *defaultFeed) SearchES(ctx context.Context, in *EsSearchReq, opts ...grpc.CallOption) (*EsSearchResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.SearchES(ctx, in, opts...)
}

func (m *defaultFeed) FindVideo(ctx context.Context, in *FindVideoReq, opts ...grpc.CallOption) (*FindVideoResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.FindVideo(ctx, in, opts...)
}
